[BACKLOG-36851] : Focus Visible - Accessibility -  PUC Home Page –Dat…
pentaho/data-access pull request #1192
Opened 2023-04-07 13:33 UTC by addagudi

…a Source Wizard (SQL Query)

2023-04-07 13:34 UTC, addagudi commented
@pentaho/wcag Please review

2023-04-07 13:43 UTC, buildguy commented
### :white_check_mark: Build finished in 10m 2s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
:ok_hand: All tests passed!
 
Tests run: **359**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/data-access-plugin/job/PR-1192/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-04-07 13:58 UTC, buildguy commented
### :white_check_mark: Build finished in 14m 49s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
:ok_hand: All tests passed!
 
Tests run: **359**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/data-access-plugin/job/PR-1192/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-04-10 12:29 UTC, dcleao requested changes

2023-04-10 12:29 UTC, dcleao commented on core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/controllers/WizardRelationalDatasourceController.java
> +          previewResultsDialog.center();
Should this not be added in line 306?
In case of error, does it make sense to show the dialog?

2023-04-11 07:48 UTC, buildguy commented
### :white_check_mark: Build finished in 9m 3s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
:ok_hand: All tests passed!
 
Tests run: **359**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/data-access-plugin/job/PR-1192/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-04-11 10:19 UTC, merged