[BACKLOG-36862] - Page Zoom (AA) - Database Connection Dialog
pentaho/data-access pull request #1208
Opened 2023-05-31 16:21 UTC by Pancho7

@pentaho/millenniumfalcon and @pentaho/wcag please review.

This PR needs to be merged with:
[https://github.com/pentaho/pentaho-commons-gwt-modules/pull/934](https://github.com/pentaho/pentaho-commons-gwt-modules/pull/934)
and
[https://github.com/pentaho/pentaho-commons-database/pull/231](https://github.com/pentaho/pentaho-commons-database/pull/231)

2023-05-31 16:29 UTC, buildguy commented
### :white_check_mark: Build finished in 8m 28s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
:ok_hand: All tests passed!
 
Tests run: **359**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/data-access-plugin/job/PR-1208/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-05-31 16:47 UTC, davidmsantos90 requested changes

2023-05-31 16:47 UTC, davidmsantos90 commented on core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/public/datasourceEditorDialog.css
> -}
This css file is not exclusive to the `ruby` theme, so this selector should not be removed.
You can override it with something like this:
```
#database-options-box input {
  width: 260px !important;
}
:where(.responsive) #database-options-box input {
  width: auto !important;
}
```

2023-06-02 14:59 UTC, davidmsantos90 approved these changes

2023-06-02 15:09 UTC, mbrasil approved these changes

2023-06-06 10:18 UTC, merged