[BACKLOG-37742] Page Zoom (AA) - Data Source Wizard Dialog-Database tables subsequent dialogs
pentaho/data-access pull request #1210
Opened 2023-06-13 08:23 UTC by varuntangirala

@pentaho/wcag Please review

This PR is part of 
https://github.com/pentaho/pentaho-analyzer/pull/2447
https://github.com/pentaho/pentaho-commons-gwt-modules/pull/939

2023-06-16 15:55 UTC, buildguy commented
### :white_check_mark: Build finished in 7m 20s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
:ok_hand: All tests passed!
 
Tests run: **359**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/data-access-plugin/job/PR-1210/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-06-16 17:26 UTC, dcleao requested changes

2023-06-16 17:26 UTC, dcleao commented on core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/public/main_wizard_panel.xul
> +            <vbox id="availableTablesBox" flex="1" pen:classname="with-scroll-h-child">
Label should also have `multiline="false"`.

2023-06-16 19:48 UTC, dcleao approved these changes

2023-06-16 19:55 UTC, buildguy commented
### :white_check_mark: Build finished in 7m 32s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
:ok_hand: All tests passed!
 
Tests run: **359**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/data-access-plugin/job/PR-1210/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-06-19 08:01 UTC, soagarwal1 approved these changes

2023-06-19 08:03 UTC, merged