[BACKLOG-37966] Toolbar improvements for PIR+PDD
pentaho/data-access pull request #1227
Opened 2023-09-29 11:29 UTC by AAravind27

@pentaho/wcag , Please Review.

Following XUL file is used for a toolbar which is used In PIR as well as PDD

2023-09-29 11:47 UTC, buildguy commented
### :white_check_mark: Build finished in 16m 49s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
:ok_hand: All tests passed!
 
Tests run: **359**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/data-access-plugin/job/PR-1227/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-09-29 20:09 UTC, dcleao requested changes

2023-09-29 20:09 UTC, dcleao commented on core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/public/datasourceSelectionDialog.xul
> +        <toolbarbutton id="editDatasource" image="images/spacer.gif" tooltiptext="${datasourceSelectionDialog.edit}"
Are all the attributes supported by `button` also supported by `toolbarbutton`?

2023-10-03 15:38 UTC, buildguy commented
### :white_check_mark: Build finished in 20m 14s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
:ok_hand: All tests passed!
 
Tests run: **359**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/data-access-plugin/job/PR-1227/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-10-04 11:14 UTC, dcleao approved these changes

2023-10-10 05:04 UTC, hv-vamsi approved these changes

2023-10-10 05:12 UTC, merged