[PPP-4865] - Vulnerable Component: snakeyaml
pentaho/data-access pull request #1257
Opened 2024-03-15 16:26 UTC by andreramos89

@smmribeiro 
@renato-s

2024-03-15 16:27 UTC, buildguy commented
### :x: Build failed in 30s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -Djs.no.sandbox
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

2024-03-18 14:33 UTC, buildguy commented
### :x: Build failed in 29s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -Djs.no.sandbox
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

2024-03-26 17:44 UTC, smmribeiro requested changes

2024-03-26 17:44 UTC, smmribeiro commented on core/pom.xml
> +      <version>${safeyaml.version}</version>
Shouldn't this be test-scoped?

2024-04-02 09:01 UTC, buildguy commented
### :x: Build failed in 30s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

2024-04-02 09:27 UTC, smmribeiro approved these changes
Looks good.

2024-04-03 15:16 UTC, merged